VAR APP = ANGULAR.MODULE('ANGULARPOSTPHP', []);
APP.CONTROLLER('LOGINCTRL', FUNCTION ($SCOPE, $HTTP) {
$SCOPE.LOGIN = FUNCTION () {
VAR REQUEST = $HTTP({
METHOD: "POST",
URL: "LOGIN.PHP",
DATA: {
EMAIL: $SCOPE.EMAIL,
PASSWORD: $SCOPE.PASSWORD
},
HEADERS: { 'CONTENT-TYPE': 'APPLICATION/X-WWW-FORM-URLENCODED' }
});
/* SUCCESSFUL HTTP POST REQUEST OR NOT */
REQUEST.SUCCESS(FUNCTION (DATA) {
IF(DATA == "1"){
$SCOPE.RESPONSEMESSAGE = "SUCCESSFULLY LOGGED IN";
}
ELSE {
$SCOPE.RESPONSEMESSAGE = "USERNAME OR PASSWORD IS INCORRECT";
}
});
}
});